version: "3"
services: 
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: owner_password
      POSTGRES_USER: hn_owner
      POSTGRES_DB: hn
  api:
    image: hookah-notes-api
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      SERVER_PORT: 8081
      DB_HOST: db
      REDIS_HOST: redis
      JWT_ACCESS_SECRET: rs+z0eovX/fFVQ7W5FNZzsg8w4mZV0J7PYp+WksKDw141sMA1gCz3ghRF1ldb5ukbQVtgT9WloCW8AldDg3iYvTDM5JAe63K/uLX5m+iG7vzJc2rzShrmJSlWn6GsfUtkkfCnTLFYZPjNrrcpROycoHXnQG8TbcL15OwK67fNLm2oHCnq8uvwo7rpqkAXzoOF4Q/Ae45dnBnFmLryeLl4oOlEsZpp+UF0GRzv6W51pZOqki30P17P9HYEq6ESgyj7rX00stuuKd2QXCfxYDKjrOFspvnFnd8Txh8degUlHVNUj2QmKIrlT3L38qifqTYubRoc+IVUFmNXzDVqpjnWw==
      JWT_REFRESH_SECRET: Z3WeSTSk64ub1zGdYxLMLZwWG9i2xpSFLXzMlrdgyr9VlzdN6cH5AYMuwFDfzTOFOJlV6jymyenfcq3JecH2NcF1s2hBo2LEjyvvcUaGdf5+nZuW6m4WbLebB2b3AxkuNw732YXUK5+/PuaChgWDgzauCKLpq9BefQpyeLPbBmUJ00voZA6JcZSpZVzDF60osT9Rz9O7JWvoIFHe5USSj3XT/njjn9/djINgCL/xnIyNU+aExo0gfmnTRtqW5NQnW6vUNDeCODX7pFVVuk/NV2ArwErRzeo/PEQ1mcSE8XRYx8IzvMGTPS1Ys6LSFZsz+ubSYBbTm8XuZxMjU5NAXw==
      CLIENT_URI: https://localhost:8443
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
networks:
  webnet: